# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d6d0ccb4ae030a48b07c89c3d2bebb7d3cb4e82fa0117e6ef57537b6973c0f89e017caad3d238375245b15d303ec5f61da0e739feea1943f6eb9e7de77ea68

test:
  secret_key_base: 4ed1cf1b9ded403754929004c24d1e248324f730d323b1d6e17246bec326ba6ec9765479d345f768d094c8da3d476dd2d018367ffd298e64897144ef18a3ad46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
